#!/bin/bash

# curl me in by:
# $ curl 'https://raw.githubusercontent.com/vindennl48/dotfiles/master/arch_install' > arch_install
# $ chmod a+x arch_install

echo "     :::     :::::::::   ::::::::  :::    ::: "
echo "   :+: :+:   :+:    :+: :+:    :+: :+:    :+: "
echo "  +:+   +:+  +:+    +:+ +:+        +:+    +:+ "
echo " +#++:++#++: +#++:++#:  +#+        +#++:++#++ "
echo " +#+     +#+ +#+    +#+ +#+        +#+    +#+ "
echo " #+#     #+# #+#    #+# #+#    #+# #+#    #+# "
echo " ###     ### ###    ###  ########  ###    ### "

read -p "Rady to install? If yes (y), If no (CTRL+C)." choice

DISK='sda'        # change this to desired drive
BOOT_SIZE='+200M'
ROOT_SIZE=''      # '' will select default size

function pre_install {
timedatectl set-ntp true
fdisk /dev/$DISK <<EOF
o
n
p
1

$BOOT_SIZE
a
n
p
2

$ROOT_SIZE
p
w
EOF

mkfs.ext4 /dev/"$DISK"1
mkfs.ext4 /dev/"$DISK"2

mount /dev/"$DISK"2 /mnt
mkdir /mnt/boot /mnt/home
mount /dev/"$DISK"1 /mnt/boot

pacstrap /mnt linux linux-firmware base base-devel networkmanager vim nano 

genfstab -U /mnt >> /mnt/etc/fstab

cp arch_install /mnt/.
echo "----> You must edit the copied installer in /mnt to uncomment 'post_install' and comment 'pre_install' at the bottom, then run."
arch-chroot /mnt
}

function post_install {
systemctl enable NetworkManager

mkinitcpio -p linux

# clean up mirrorlist
curl "https://www.archlinux.org/mirrorlist/?country=GB" -o /etc/pacman.d/mirrorlist

# install grub bootloader
pacman -S --needed --noconfirm grub
grub-install --target=i386-pc /dev/"$DISK"
grub-mkconfig -o /boot/grub/grub.cfg

# set root password
echo    "----> Set password for root"
read -p "      (Press ENTER to continue)" choice
passwd

# set locale & timezone
echo    "----> Set locales, uncomment all en_GB"
read -p "      (Press ENTER to continue)" choice
vim /etc/locale.gen
locale-gen
echo "LANG=en_GB.UTF-8" > /etc/locale.conf
ln -sf /usr/share/zoneinfo/GMT /etc/localtime

# set hostname
echo "entity" > /etc/hostname

# add main user
echo    "----> Add first user: " 
read firstUser
useradd -m $firsUser -g wheel,audio,video,optical,storage

echo    "----> Set wheel permissions: uncomment 'wheel ALL=(ALL) ALL' and add 'Defaults !tty_tickets'"
read -p "      (Press ENTER to continue)" choice
vim /etc/sudoers

echo    "----> Make sure to exit to main screen and un-mount /mnt/boot"
echo    "      then /mnt then shutdown now"
read -p "      (Press ENTER to continue)" choice
}

# Comment out the one you are NOT installing
pre_install
#post_install

